[project]
name = "bass-map"
version = "0.1.0"
description = "Creates a .csv of pub names and coordinates from the National Bass Directory"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "camelot-py>=1.0.9",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
