name: Create pub locations csv

on:
  workflow_dispatch:   # allows manual runs
  schedule:            # run at 1pm UTC on the 1st of every month
    - cron: "0 13 1 * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install uv

      - name: Get API token
        run: echo "GOOGLE_MAPS_API=${{ secrets.GOOGLE_MAPS_API }}" >> $GITHUB_ENV

      - name: Run script
        run: uv run python main.py

      - name: Upload permanent Bass locations csv
        uses: actions/upload-artifact@v4
        with:
          name: permanent-location
          path: "*.csv"