name: Create pub locations csv

on:
  workflow_dispatch:   # allows manual runs
  schedule:            # run at 1pm UTC on the 1st of every month
    - cron: "0 13 1 * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install uv

      - name: Get API token
        run: echo "GOOGLE_MAPS_API=${{ secrets.GOOGLE_MAPS_API }}" >> $GITHUB_ENV

      - name: Run script
        run: uv run python main.py

      # Commit and push all CSV files
      - name: Commit and push CSVs
        run: |

          # Add all CSV files recursively
          git add ./outputs

          # Commit if there are changes
          git diff --cached --quiet || git commit -m "Update generated CSVs [skip ci]"

          # Push to main
          git push origin main
      - name: Commit files # commit the output folder
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add ./output
          git commit -m "Update csvs"
          git push