name: Generate and Commit CSVs

on:
  workflow_dispatch:

permissions:
  contents: write  # needed for pushing changes

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install uv

      # 4. Run the pub location finding script
      - name: Generate CSVs
        run: uv run python main.py

      # 5. Upload CSVs as workflow artifacts
      - name: Upload CSVs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-outputs
          path: outputs/*.csv

      # 6. Commit and push CSVs back to main branch
      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add outputs
          git diff --cached --quiet || git commit -m "Update CSVs [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
