name: Publish CSVs to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages
  pages: write      # needed to publish GitHub Pages
  id-token: write   # needed for OIDC auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install uv

      - name: Run script
        run: uv run python bass_map/test.py

      # Upload the outputs folder as a GitHub Pages artifact
      - name: Upload CSVs as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: outputs

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
