name: Test committing a csv

on:
  workflow_dispatch:   # allows manual runs
jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install uv

      - name: Run script
        run: uv run python bass_map/test.py

      # Commit and push all CSV files
      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ./outputs
          git diff --cached --quiet || git commit -m "Update CSVs for GitHub Pages [skip ci]"
          git push origin main